wait_data <- read.table('waittime.dat', header=T, sep="\t")
png(filename="waittime.png", bg="white")
plot(wait_data$Seconds, type="o", col="blue", ann=FALSE, axes=FALSE)
axis(1, at=1:12, lab=wait_data$Date)
axis(2, las=1)
title("Job Waittime")
title(xlab="Date", font.main="4", col.lab=rgb(0,0.5,0))
title(ylab="Wallclock Seconds", font.main="4", col.lab=rgb(0,0.5,0))
box()
dev.off()
