data    <- read.table('report.dat', header=T, sep=",")
u_range <- range(0, data$total_jobs)

pdf('report.pdf')
plot(data$total_jobs,  type="o", lwd=2, lty=1, pch=NA, col="blue", ann=F, axes=F, ylim=u_range)
axis(1, 1:52, lab=T)
axis(2, at=axTicks(2), labels=seq(0, length(axTicks(2))^2, 5), cex=0.8, tick=TRUE, line=NA, pos=NA)
title(ylab="Jobs")
box()
dev.off()
